name: rfs-parts-db
version: 1.2.4
summary: Python-based parts database handler for Rexroth ctrlX AUTOMATION RFS platform 
# title: SDK-Python
description: 'rfs-parts-db provides a parts database handler (SQLite) for Rexroth ctrlX AUTOMATION platform 
'
base: core20
confinement: strict
grade: stable

architectures:
  - build-on: arm64

apps:
  interpreter:
    #command: python3
    command: python    
    plugs:
      - network-bind
      - network-observe
      - serial-port

  provider:
    command: ./wrapper/register_job_queue
    plugs:
      - network-bind
      - network-status
      - removable-media
    daemon: simple

parts:
  rfs-parts-db:
    plugin: python
    source: .
    python-packages:
      - jsonschema
      - ctrlx-datalayer
      - ctrlx-fbs
      - flatbuffers~=1.12


# describes which interface slots are supported by defining the plugs
plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer 


# parts:
#   interpreter:
#     plugin: python
#     source: .
#      python-packages:
#       - jsonschema

#   provider:
#     plugin: python
#     source: .
#     python-packages:
#       - ./whl/ctrlx_datalayer-1.4.0-py3-none-any.whl
#       - ./whl/ctrlx_fbs-1.0.0-py3-none-any.whl
#       - flatbuffers~=1.12

#   files:
#     plugin: dump
#     source: . 

