name: rfs-parts-db
version: 1.3.9
summary: Python-based parts database handler for Rexroth ctrlX AUTOMATION RFS platform 
title: rfs-parts-db
description: |
  rfs-parts-db provides a parts database handler (SQLite) for Rexroth ctrlX AUTOMATION platform
base: core20
confinement: strict
grade: stable

architectures:
  - build-on: arm64

apps:
  provider:
    command: bin/main.py
    plugs:
      - network
      - datalayer
      - removable-media      
    daemon: simple
    restart-condition: always
    passthrough:   
      restart-delay: 10s

parts:
  provider:
    plugin: python
    source: .

plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer 



